### ISSUE TITLE
did you try .glb modle？

### ISSUE THREAD

**Issue by fzw2408** [AIFanatic/three-nanite#2]
有挺多情况需要处理
1.  demo 本身是不是只考虑了模型单一的mesh的分解成meshlet。如果是若个mesh的话分解是不是意味着需要将多个mesh合并【merge】 后在分解成小型的meshlet？
2. 模型网格面过多的话会有递归死循环，
3.对glb模型的支持。
4.three-nanite 目前只争对单一模型做meshelet的分解和lod加载管理，是否有考虑全场景模型的meshlet的lod管理呢？思路是否是将整个场景网格合并后在做meshlet分解？还是各自为分解？可否达到UE5的nanite的效果呢？
 

i use blender :
bundy.obj =>bundy.glb

GlbLoaderIndexed.ts 【these seem has some issue】 

```typescript
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { MeshoptDecoder } from './utils/js/meshopt_decoder.module.js'; 
// 
interface UnpackedAttrs {
    verts: number[];
    hashindices: { [k: string]: number };
    indices: number[][];
    index: number;
}

export interface OBJMesh {
    vertices: Float32Array,
    indices: Uint32Array
};

export class GlbLoaderIndexed {
    public static* triangulate(elements: string[]) {
        if (elements.length <= 3) {
            yield elements;
        } else if (elements.length === 4) {
            yield [elements[0], elements[1], elements[2]];
            yield [elements[2], elements[3], elements[0]];
        } else {
            for (let i = 1; i < elements.length - 1; i++) {
                yield [elements[0], elements[i], elements[i + 1]];
            }
        }
    }
    
    public static load(url: string, callback: (contents: OBJMesh) => void) {
        // fetch(url).then(response => response.text()).then(contents => callback(GlbLoaderIndexed.parse(contents)));


        var loader = new GLTFLoader();
        loader.setMeshoptDecoder(MeshoptDecoder);               
        loader.load(url, function (gltf) {
            let totalFaces = 0;  
            let objMesh = {} as OBJMesh;                                                     
            gltf.scene.traverse(function (object) {
                if (object.isMesh) { 
                    if(objMesh.vertices=== undefined)                 {
                        objMesh.vertices = new Float32Array( object.geometry.attributes.position.array)   ;
                    }else{                        
                        let mergedArray =[...objMesh.vertices,...object.geometry.attributes.position.array];     
                        objMesh.vertices = mergedArray ;
                    } 
                    if( objMesh.indices === undefined){
                        objMesh.indices = new Uint32Array( object.geometry.index.array) ;
                    }else{ 
                        let mergedArray =[...objMesh.indices,...object.geometry.index.array];                          
                        objMesh.indices = mergedArray  ;
                    } 
                                       
                }					 
            });
            
            callback(objMesh);          
        }) ;
    }
 
  
}
```

**Comment by AIFanatic** [comment]
If i understood your question correctly you are asking how can a whole scene be managed.
three-nanite and, to my understanding, UE5 nanite always works on a single mesh.

You convert a single mesh to meshlets and render it. If you have different meshes (different meaning actually different geometry) you create meshlets for each one of them just like you would create separate meshes with THREE.js.

Keep in mind that the current code provides something akin of InstancedMesh, as you can see in the example there are 20*20 bunnies but only one drawCall, but if you had for example 20 bunnies and 20 trees it would be 2 drawCalls.

Also keep in mind that some models fail and i haven't gotten to sorting it out, its an issue with on how adjacency meshlets are calculated since not all meshes are equal (manifold etc).

As for merging geometries it doesn't seem advisable since you wont be able to frustum cull as easily. Nanite is awesome because no modifications/tricks have to be made to the model or geometries, everything is done automatically behind the scenes.

**Comment by fzw2408** [comment]
thanks a lot
