### ISSUE TITLE
Is the project still being maintained?

### ISSUE THREAD

**Issue by ademola-lou** [AIFanatic/three-nanite#3]
Hello, 

This is really incredible! I want to use it for my project.

Just curious if this code is still being maintained ?

Best regards

**Comment by AIFanatic** [comment]
Hi, thanks.
The current bottleneck of the project is the testLod method which is done on the cpu and scales with the number of individual meshlets on the scene, the algorithm can be ported to the gpu but it would benefit a lot from drawIndirect (webgpu) but threejs does not support it yet (https://github.com/mrdoob/three.js/issues/28389). To make it work with webgl quite some hacks are needed and i dont think we can get away from at least one gpu->cpu->gpu trip which is expensive. Some type of broad and narrow phase test can also be experimented with to increase its performance.
Other than that the code can be cleaned:
* Integrate the meshlet generation simplification etc into one MeshletMesh class to make it more streamline with the threejs api.
* Port the wasm code (meshoptimizer/metis) to typescript in order to be dependency free.
* Relevant to the point above, ideally, get rid of metis since meshoptimizer has a meshlet generation method, albeit not as good.

Specifically in terms of code maintenance the above can be done but having the testLod bottleneck kinda makes the cleanup a bit pointless, PR's are welcomed though.
I may revisit the project in the future since it seems to be getting some attention.

**Comment by ademola-lou** [comment]
I think meshoptimizer recent release now has a good meshlet generation. I will love to contribute, also I can't wait for Mesh shader to be supported on webgpu; this will enable us to draw triangles directly and make culling easier! I'm hoping other three.js developers will love to contribute to this amazing project.

Cheers!

**Comment by Spiri0** [comment]
You could also use compute shaders for that, right? I use these very extensively in my Ocean2 repo. 
I recalculate the wave spectrum of the ocean at every interval using computer shaders. The data saves my compute shader in f32 textures. Vertex shader and fragment shader can access these directly. The performance with the huge amounts of data is impressive.
I've long wanted to make the ocean transparent with scattering so that you can authentically see underwater objects, but I just don't have the time. I'm very busy with my new mars project.
I trimmed your repo to WebGPU because I only work with WebGPU in three.js.
I don't want to make any promises that I can't keep due to time constraints, but I'm very familiar with WebGPU in three.js and I'd like to help if I can.

**Comment by VeinSyct** [comment]
Yes this is still being maintained, see threejs project https://discourse.threejs.org/t/virtually-geometric/28420/58
